## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [18]:
# okay numpy is great but... how would you inverse a matrix by hand?

def inverse_matrix(A):
    return np.linalg.inv(A)

a = np.array([[7, -5, 10], [-9, 4, 8], [2.8, 1, -8]])
b = np.array([[8, 0, 10], [5, 2.9, 0.5], [8, -1, 4]])
c = np.dot(a, b)
print(c)

c23 = c[1, 2]
print(f'What is the value of element c23​ of Matrix C where C=A x B ? {c23}')

[[111.  -24.5 107.5]
 [ 12.    3.6 -56. ]
 [-36.6  10.9  -3.5]]
What is the value of element c23​ of Matrix C where C=A x B ? -56.0


In [19]:
def inverse_matrix(A):
    return np.linalg.inv(A)

a = np.array([[7, -5, 10], [-9, 4, 8], [2.8, 1, -8]])
b = np.array([[8, 0, 10], [5, 2.9, 0.5], [8, -1, 4]])
c = np.dot(b, a)
print(c)

c23 = c[1, 2]
print(f'What is the value of element c23​ of Matrix C where C= B x A ? {c23}')

[[ 84.  -30.    0. ]
 [ 10.3 -12.9  69.2]
 [ 76.2 -40.   40. ]]
What is the value of element c23​ of Matrix C where C= B x A ? 69.2


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [4]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [17]:
row = c.shape[0]
print(f'How many rows will C have?  {row}')

columns = c.shape[1]
print(f'How many columns will C have?  {columns}')

c13 = c[0, 2]
print(f'What will be the value of c13​? {c13}')

How many rows will C have?  3
How many columns will C have?  3
What will be the value of c13​? 107.5
