# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [104]:
import numpy as np

In [105]:
def add_vectors(u, v):
    """
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
    """
    pass


In [106]:
a = np.array([1, 0])
b = np.array([1, 1])
print(a + b)

a1 = np.array([1, 2])
b1 = np.array([1, 4])
print(a1 + b1)

a2 = np.array([1, 2, 1])
b2 = np.array([1, 4, 3])
print(a2 + b2)

a3 = np.array([11, 0, -4, 5])
b3 = np.array([2, -4, 17, 0])
print(a3 + b3)

a4 = np.array([1, 2, 3])
b4 = np.array([1, 1, 1])
add_vectors(a4, b4)
print(a4 + b4)
print(a4)
print(b4) 

[2 1]
[2 6]
[2 6 4]
[13 -4 13  5]
[2 3 4]
[1 2 3]
[1 1 1]


Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [107]:
def scalar_mult(s, v):
    """
      >>> scalar_mult(5, [1, 2])
      [5, 10]
      >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
    """
    pass

In [108]:
a = np.array([1, 2])
print(5 * a)

a1 = np.array([1, 0, -1])
print(3 * a1)

a2 = np.array([3, 0, 5, 11, 2])
print(7 * a2)

a3 = np.array([1, 2, 3])
print(4 * a3)
print(a3)

[ 5 10]
[ 3  0 -3]
[21  0 35 77 14]
[ 4  8 12]
[1 2 3]


Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [109]:
def dot_product(u, v):
    """
      >>> dot_product([1, 1], [1, 1])
      2
      >>> dot_product([1, 2], [1, 4])
      9
      >>> dot_product([1, 2, 1], [1, 4, 3])
      12
      >>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
      0
    """
    pass

In [110]:
a = np.array([1, 1])
b = np.array([1, 1])
d = np.dot(a, b)
print(d)

a1 = np.array([1, 2])
b1 = np.array([1, 4])
d1 = np.dot(a1, b1)
print(d1)

a2 = np.array([1, 2, 1])
b2 = np.array([1, 4, 3])
d2 = np.dot(a2, b2)
print(d2)

a3 = np.array([2, 0, -1, 1])
b3 = np.array([1, 5, 2, 0])
d3 = np.dot(a3, b3)
print(d3)

2
9
12
0


## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [111]:
def copy_matrix(matrix):
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """
    pass

In [112]:
a = np.array([[1, 2], [3, 4]])
print(a)

a1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a1)

a2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(a2)

m = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
print(m)
copyofm = copy_matrix(m)
copyofm = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
[row_num] = copyofm
[col_num] = [row_num]
copyofm[row_num][col_num] = 42
print(copyofm)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


ValueError: too many values to unpack (expected 1)

In [ ]:
def add_row(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """
    pass

In [ ]:
m = np.array([[0, 0], [0, 0]])
row = np.array([0, 0])
arr = np.r_[m,[row]]
print(arr)

n = np.array([[3, 2, 5], [1, 4, 7]])
row = np.array([0, 0, 0])
arr1 = np.r_[n,[row]]
print(arr1)
print(n)


[[0 0]
 [0 0]
 [0 0]]
[[3 2 5]
 [1 4 7]
 [0 0 0]]
[[3 2 5]
 [1 4 7]]


In [ ]:
def add_column(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """
    pass

In [ ]:
m = np.array([[0, 0], [0, 0]])
array = np.append(m, [[0],[0]], axis = 1)
print(array)

n = np.array([[3, 2], [5, 1], [4, 7]])
array1 = np.append(n, [[0],[0],[0]], axis = 1)
print(array1)
print(n)

[[0 0 0]
 [0 0 0]]
[[3 2 0]
 [5 1 0]
 [4 7 0]]
[[3 2]
 [5 1]
 [4 7]]


Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [ ]:
def add_matrices(m1, m2):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> b = [[2, 2], [2, 2]]
      >>> add_matrices(a, b)
      [[3, 4], [5, 6]]
      >>> c = [[8, 2], [3, 4], [5, 7]]
      >>> d = [[3, 2], [9, 2], [10, 12]]
      >>> add_matrices(c, d)
      [[11, 4], [12, 6], [15, 19]]
      >>> c
      [[8, 2], [3, 4], [5, 7]]
      >>> d
      [[3, 2], [9, 2], [10, 12]]
   """
    pass

In [115]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 2], [2, 2]])
print(a + b)

a1 = np.array([[8, 2], [3, 4], [5, 7]])
b1 = np.array([[3, 2], [9, 2], [10, 12]])
print(a1 + b1)
print(a1)
print(b1)


[[3 4]
 [5 6]]
[[11  4]
 [12  6]
 [15 19]]
[[8 2]
 [3 4]
 [5 7]]
[[ 3  2]
 [ 9  2]
 [10 12]]


Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [ ]:
def scalar_mult(s, m):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
    """
    pass

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(3 * a)

a1 = np.array([[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]])
print(10 * a1)
print(a1)

[[ 3  6]
 [ 9 12]]
[[30 50 70]
 [10 10 10]
 [ 0 20  0]
 [20 20 30]]
[[3 5 7]
 [1 1 1]
 [0 2 0]
 [2 2 3]]


Write functions row_times_column and matrix_mult:

In [ ]:
def row_times_column(m1, row, m2, column):
    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """
    pass

In [ ]:
a = np.array([[1, 2], [3,  4]])
b = np.array([[5, 6], [7, 8]])
d = np.dot(a , b)
print(d)

[[19 22]
 [43 50]]


In [ ]:
def matrix_mult(m1, m2):
    """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """
    pass

In [114]:
a = np.array([[1, 2], [3,  4]])
b = np.array([[5, 6], [7, 8]])
d = np.dot(a , b)
print(d)

a1 = np.array([[1, 2, 3], [4,  5, 6]])
b1 = np.array([[7, 8], [9, 1], [2, 3]])
d1 = np.dot(a1 , b1)
print(d1)

a2 = np.array([[7, 8], [9, 1], [2, 3]])
b2 = np.array([[1, 2, 3], [4, 5, 6]])
d2 = np.dot(a2 , b2)
print(d2)

[[19 22]
 [43 50]]
[[31 19]
 [85 55]]
[[39 54 69]
 [13 23 33]
 [14 19 24]]


Write a function transpose that takes a matrix as an argument and returns is transpose:

In [ ]:
def transpose(m):
    """
     >>> m = [[3, 4, 6]]
     >>> transpose(m)
     [[3], [4], [6]]
     >>> m
     [3, 4, 6]
     >>> m = [[3, 4, 6], [1, 5, 9]]
     >>> transpose(m)
     [[3, 1], [4, 5], [6, 9]]
   """
    pass

In [113]:
a = np.array([[3, 4, 6]])
print(a.transpose())
print(a)

a1 = np.array([[3, 4, 6], [1, 5, 9]])
print(a1.transpose())


[[3]
 [4]
 [6]]
[[3 4 6]]
[[3 1]
 [4 5]
 [6 9]]
