#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [11]:
import numpy as np

from numpy import random

x = random.rand(10,10)
a = np.amin(x)
b = np.amax(x)

print(a,b)


0.010988501465665323 0.9991477731738954


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
import numpy as np
x = np.ones((5,5))
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
